"""Deterministic replay of identical nominal commands OFF/ON, no hardware."""
import argparse
from dataclasses import asdict
import json
from pathlib import Path
import numpy as np
from orca_sim import OrcaHandRight
from orca_safety_v2.teleop import SimulationCollisionSafety
from orca_safety_v2.adapter import build_sim_model


def stats(x):
    a=np.asarray(x,dtype=float)
    return dict(mean=float(a.mean()),median=float(np.median(a)),p95=float(np.percentile(a,95)),maximum=float(a.max()))


def main():
    p=argparse.ArgumentParser();p.add_argument('--steps',type=int,default=120)
    p.add_argument('--replay',type=Path,help='NPZ generated by generate_retarget_replay.py')
    p.add_argument('--poses',type=Path,default=Path(__file__).resolve().parents[1]/'output/passive/poses.json')
    p.add_argument('--output',type=Path,default=Path('output/comparison'));args=p.parse_args()
    if args.steps<10:p.error('--steps must be >=10')
    args.output.mkdir(parents=True,exist_ok=True)
    poses={k:np.array(v) for k,v in json.loads(args.poses.read_text()).items()}
    q0=poses['open'];motions=dict(poses)
    probe=OrcaHandRight(version='v1');model,*_=build_sim_model(probe);probe.close()
    index={n.removeprefix('right_'):i for i,n in enumerate(model.joint_names)}
    spread=q0.copy()
    for name,value in zip(['index_abd','middle_abd','ring_abd','pinky_abd'],[-.8,-.3,.5,.9]):spread[index[name]]=value
    motions['spread']=spread
    # Fixed replay surrogate, not a recording of the assembly task.
    assembly=q0.copy()
    for finger,mcp,pip in [('index',.4,.8),('middle',.45,.8),('ring',.5,.9),('pinky',.6,1.)]:
        assembly[index[finger+'_mcp']]=mcp;assembly[index[finger+'_pip']]=pip
    motions['assembly_like_synthetic']=assembly
    replay=None
    if args.replay:
        with np.load(args.replay) as data:
            if list(data['joint_names'])!=list(model.joint_names):raise ValueError('Replay joint order mismatch')
            replay=data['q_nominal'].copy()
        if replay.ndim!=2 or replay.shape[1]!=len(q0) or not np.all(np.isfinite(replay)):
            raise ValueError('Invalid replay')
        motions={'adaptive_analytical_replay':q0};args.steps=len(replay)
    report={'steps_per_motion':args.steps,'robot':'v1_right','safe_distance':.005,
            'source':'synthetic absolute-radian targets, identical OFF/ON; not live MediaPipe',
            'motions':{}}
    if replay is not None:report['source']='unchanged adaptive_analytical outputs from synthetic 21-point landmarks, identical OFF/ON'
    for name,target in motions.items():
        # Smooth open -> target -> open with a short hold, in identical simulation time.
        phase=np.linspace(0,1,args.steps)
        alpha=np.minimum(np.minimum(phase/.35,(1-phase)/.35),1)
        trajectory=q0[None,:]+alpha[:,None]*(target-q0)[None,:]
        if name=='open':trajectory[:]=q0
        if replay is not None:trajectory=replay
        np.save(args.output/f'{name}-nominal.npy',trajectory)
        outcomes={}
        for enabled in [False,True]:
            mode='ON' if enabled else 'OFF'
            env=OrcaHandRight(version='v1');env.reset()
            runner=SimulationCollisionSafety(env,log_path=args.output/f'{name}-{mode}.jsonl',monitor_only=not enabled)
            rows=[]
            for q in trajectory:rows.append(runner.dispatch(q))
            runner.close();env.close()
            distance=[r['min_distance_measured'] for r in rows]
            result={'mean_min_distance':float(np.mean(distance)),'minimum_distance':float(min(distance)),
                    'margin_violation_rate':float(np.mean([r['measured_margin_violation'] for r in rows])),
                    'collision_rate':float(np.mean([r['measured_collision'] for r in rows])),
                    'intervention_rate':float(np.mean([r['intervention_norm']>1e-5 for r in rows])),
                    'intervention_norm':stats([r['intervention_norm'] for r in rows]),
                    'fallbacks':sum(r['fallback'] for r in rows)}
            if enabled:
                result['timings']={k:stats([r[k] for r in rows]) for k in ['distance_time_ms','gradient_time_ms','solver_time_ms','total_safety_time_ms']}
                result['solver']={'calls':len(rows),'solved':sum(r['solver_status']=='solved' for r in rows),
                                  'infeasible':sum('infeasible' in r['solver_status'] for r in rows),
                                  'failures':sum(r['solver_status']!='solved' for r in rows),
                                  'mean_iterations':float(np.mean([r['solver_iterations'] for r in rows]))}
            outcomes[mode]=result
            print(name,mode,'collision',result['collision_rate'],'margin',result['margin_violation_rate'],'fallbacks',result['fallbacks'],flush=True)
        report['motions'][name]=outcomes
        (args.output/'summary.json').write_text(json.dumps(report,indent=2))

if __name__=='__main__':main()
